name: ROS2 CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Cette étape fonctionne sur un environnement Ubuntu géré par GitHub Actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up ROS 2 Foxy
      run: |
        sudo apt update
        sudo apt install -y curl gnupg2 lsb-release
        curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://packages.ros.org/ros2/ubuntu $(lsb_release -c | awk "{print $2}") main" > /etc/apt/sources.list.d/ros2.list'
        sudo apt update
        sudo apt install -y ros-foxy-desktop
        source /opt/ros/foxy/setup.bash
        mkdir -p ~/ros2_ws/src
        cd ~/ros2_ws
        colcon build
        source ~/ros2_ws/install/setup.bash

    - name: Build ROS 2 workspace
      run: |
        mkdir -p ~/ros2_ws/src
        cd ~/ros2_ws
        colcon build

    - name: Run ROS 2 tests
      run: |
        source ~/ros2_ws/install/setup.bash
        ros2 run calculator_service addition_server  # Remplacez par votre nœud et service
